version: 0.0
os: linux
files:
  - source: config/config-blue.json
    destination: /webapps/config/
  - source: config/config-green.json
    destination: /webapps/config/
  - source: src/server.js
    destination: /webapps/src/
  - source: src/package.json
    destination: /webapps/src/
hooks:
  BeforeInstall:
    - location: Scripts/StopApplication.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: Scripts/InstallDependencies.sh
      timeout: 600
      runas: root
  ApplicationStart:
    - location: Scripts/StartApplication.sh
      timeout: 3600
      runas: root
  ValidateService:
    - location: Scripts/HealthCheck.sh
      timeout: 600
      runas: root
