version: 0.2

phases:
  install:
    runtime-versions:
      # Define any runtime versions you might need, like Node.js, Python, etc.
      # Here we do not need any specific runtime since it's a simple static site.
    commands:
      - echo "Installing dependencies (if any)..."

  pre_build:
    commands:
      - echo "No pre-build steps required."

  build:
    commands:
      - echo "Building the web app..."
      - mkdir -p build
      - cp -r * build/
      # This assumes that the 'index.html' file is in the root of your repository.
      # The 'build' directory will contain the web app's files for deployment.

  post_build:
    commands:
      - echo "Build completed successfully."
      - echo "The app is ready for deployment."

artifacts:
  files:
    - build/**  # Include everything inside the 'build' directory
  base-directory: build  # Define 'build' directory as the base directory to get all files for deployment
  discard-paths: yes  # Optionally discard the folder structure for simpler deployment
