version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."

  build:
    commands:
      - echo '<html>' > index.html
      - echo '<body style="background-color: blue; color: white;">' >> index.html
      - echo '<h1>Blue Version</h1>' >> index.html
      - echo '</body>' >> index.html
      - echo '</html>' >> index.html

  post_build:
    commands:
      - echo "Build complete, HTML file generated: index.html"

artifacts:
  files:
    - index.html
